---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1

verifier:
  name: inspec
  format: documentation

platforms:
  - name: windows-2008R2-cvent

suites:
  - name: server
    run_list:
      - recipe[octopus-deploy-test::server]
  - name: tentacle
    run_list:
      - recipe[octopus-deploy-test::tentacle]
  - name: tentacle_with_name
    run_list:
      - recipe[octopus-deploy-test::tentacle]
    attributes:
      octopus_deploy_test:
        username: octopus_user
